services:
  app:
    image: 'codereview/msgbackend:latest'
    build:
      context: .
    container_name: msgBackend
    links:
      - db
    networks:
      - msgbackend
    depends_on:
      - db
  db:
    image: 'postgres:13.3'
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=msgbackend
      - POSTGRES_PASSWORD=msgbackend
      - POSTGRES_DB=msgbackend
    expose:
      - 5432:5432
    networks:
      - msgbackend
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
networks:
  msgbackend: